# Generated by Django 5.0.3 on 2024-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_remove_questionset_direction'),
        ('response', '0003_alter_response_question_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='correct_answers',
            field=models.ManyToManyField(editable=False, related_name='correct_responses', to='question.choice'),
        ),
    ]
