# Generated by Django 5.0.3 on 2024-04-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='direction',
            field=models.TextField(default='not specified', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionset',
            name='title',
            field=models.CharField(default='not specified', max_length=50),
            preserve_default=False,
        ),
    ]
