# Generated by Django 5.0.3 on 2024-04-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
