# Generated by Django 5.0.3 on 2024-05-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_remove_question_answer_choice_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='direction',
        ),
    ]
