# Generated by Django 5.0.3 on 2024-05-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_remove_questionset_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
